language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
script:
  - shellcheck makeGitHookDeploy.sh
  - shellcheck setup.sh
  - shellcheck setupHelpers/node.sh
  - shellcheck setupHelpers/firewall.sh